version: "2"
services:
  consul:
    image: consul
    container_name: consul
    hostname: consul
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53"
    networks:
      - consul
  consul-sidekick:
    image: appropriate/curl
    depends_on:
      - consul
    command: sh /provision-consul.sh
    volumes:
      - ${PWD}/sidekick/provision-consul.sh:/provision-consul.sh
    networks:
      - consul
  confd:
    build:
      context: .
    image: danielpalstra/confd-demo
    command: /bin/true
networks:
  consul:
